"""Report rendering: PipelineResult -> Markdown, JSON, and files on disk.

The Markdown report is the human artifact; JSON is the machine one. Every
claim in the report carries its chunk citations, and a citation index at the
bottom resolves each chunk id to its source page and heading — a report
reader can always answer "says who, exactly where".
"""

from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Environment

from site_rag_analyst.models import PipelineResult

_TEMPLATE = """\
# Site Analysis Report

- **Site:** {{ result.url }}
- **Generated:** {{ result.report.generated_at.strftime("%Y-%m-%d %H:%M UTC") }}
- **Mode:** {{ result.mode }}{% if result.report.model %} · model: {{ result.report.model }}{% endif %}
- **Run:** {{ result.run_id }}

## Executive summary

{{ result.report.executive_summary }}

{% for section in result.report.sections %}
## {{ section.title }}

{% if section.points %}
{% for point in section.points %}
- {{ point.text }} _[{{ point.citations | join(", ") }}]_
{% endfor %}
{% else %}
_No relevant context was retrieved for this section._
{% endif %}
{% endfor %}

## Pages analyzed

| Page | Title | Words | Chunks |
|------|-------|-------|--------|
{% for page in result.report.pages %}
| {{ page.url }} | {{ page.title }} | {{ page.word_count }} | {{ page.chunk_count }} |
{% endfor %}

## Pipeline stats

| Stage | Items | Duration (s) | Detail |
|-------|-------|--------------|--------|
{% for stat in result.report.stage_stats %}
| {{ stat.stage }} | {{ stat.items }} | {{ "%.2f" | format(stat.duration_seconds) }} | {{ stat.detail }} |
{% endfor %}

## Citation index

{% for chunk in citation_index %}
- **{{ chunk.id }}** — {{ chunk.page_title }}{% if chunk.heading_path %} › {{ chunk.heading_path }}{% endif %} ({{ chunk.page_url }})
{% endfor %}

---

*Report generated by [site-rag-analyst](https://github.com/ixiami1314/site-rag-analyst){% if result.mode == "demo" %} in demo mode (offline embeddings + extractive analyst; no LLM was called){% endif %}.*
"""

_env = Environment(autoescape=False, trim_blocks=False, lstrip_blocks=True)


def render_markdown(result: PipelineResult) -> str:
    """Render the final Markdown report with a full citation index."""
    if result.report is None:
        return (
            f"# Site Analysis Report\n\n**Site:** {result.url}\n\n"
            f"Run `{result.run_id}` failed: {result.error or 'unknown error'}\n"
        )
    template = _env.from_string(_TEMPLATE)
    return template.render(result=result, citation_index=result.chunks)


def save_outputs(result: PipelineResult, directory: Path) -> Path:
    """Persist report.md, report.json and artifacts.json into ``directory``."""
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "report.md").write_text(render_markdown(result), encoding="utf-8")
    (directory / "report.json").write_text(
        json.dumps(
            result.report.model_dump(mode="json") if result.report else {},
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    (directory / "artifacts.json").write_text(
        result.model_dump_json(indent=2), encoding="utf-8"
    )
    return directory
